repos:
  - repo: git@github.com:astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: git@github.com:RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
    - id: pyright

  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
