services:
  web:
    build: .
    container_name: buddy-gym-web
    command: uvicorn buddy_gym_bot.server.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      WEBAPP_URL: "https://4c66994fe6f5.ngrok-free.app"


  bot:
    build: .
    container_name: buddy-gym-bot
    command: /app/.venv/bin/python -m buddy_gym_bot.bot.main
    depends_on:
      - web
    env_file:
      - .env
    environment:
      USE_WEBHOOK: "false"            # force polling locally
      FF_AUTO_I18N: "true"
      FF_REFERRALS: "true"
      FF_REMINDERS: "true"
      FF_SHARE_PNG: "true"
      FF_ADMIN_ALERTS: "false"
      FF_EXERCISEDB: "false"
