app = 'buddy-gym-bot'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  PLAN_DEFAULT_SPLIT = 'full_body'
  USE_WEBHOOK = 'true'
  WEBHOOK_URL = 'https://buddy-gym-bot.fly.dev/bot'
  WEBAPP_URL = 'https://buddy-gym-bot.fly.dev/webapp/'
  FF_AUTO_I18N = "true"
  FF_REFERRALS = "true"
  FF_REMINDERS = "true"
  FF_SHARE_PNG = "true"
  FF_ADMIN_ALERTS = "true"
  FF_EXERCISEDB = "true"

[processes]
  web = "uvicorn buddy_gym_bot.server.main:app --host 0.0.0.0 --port 8080"
  bot = "/app/.venv/bin/python -m buddy_gym_bot.bot.main"

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false
    grace_period = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "pybabel compile -d src/bot/locales -D messages -f"
