# fly.toml app configuration file generated for buddy-gym-bot on 2025-08-11T03:09:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'buddy-gym-bot'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  PLAN_DEFAULT_SPLIT = 'full_body'
  # USE_WEBHOOK = 'true'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
