app = "buddy-gym-postgres"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 30

[build]
  image = "postgres:17-alpine"

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql"

[env]
  # PGDATA = "/var/lib/postgresql/data"
  POSTGRES_DB = "postgres"
  POSTGRES_USER = "postgres"
  # POSTGRES_PASSWORD via secrets

[[services]]
  internal_port = 5432
  protocol = "tcp"
  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
