app = "buddy-gym-postgres"
primary_region = "iad"

[build]
  image = "postgres:17-alpine"

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[env]
  POSTGRES_DB = "postgres"
  POSTGRES_USER = "postgres"
  # POSTGRES_PASSWORD via secrets

[[services]]
  internal_port = 5432
  protocol = "tcp"
  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]
